from django.contrib import admin
from django.urls import path
from miniapp import views


urlpatterns = [
        path("",views.home),
        path('login/',views.login,name='login'),
        path('register/',views.Userregistration,name='register'),
        path('logout/',views.logout,name='logout'),
        path('home1/',views.home1),
        path('up/',views.simple_upload),
        path('cse4/', views.cse4),
        path('cse3/', views.cse3),
        path('cse2/', views.cse2),
        path('cse1/', views.cse1),
        path('eee4/', views.eee4),
        path('eee3/', views.eee3),
        path('eee2/', views.eee2),
        path('eee1/', views.eee1),
        path('ece4/', views.ece4),
        path('ece3/', views.ece3),
        path('ece2/', views.ece2),
        path('ece1/', views.ece1),
        path('it4/', views.it4),
        path('it3/', views.it3),
        path('it2/', views.it2),
        path('it1/', views.it1),  
        path('csm4/', views.csm4),
        path('csm3/', views.csm3),
        path('csm2/', views.csm2),
        path('csm1/', views.csm1),

        path('cse4rem/', views.cse4rem),
        path('cse3rem/', views.cse3rem),
        path('cse2rem/', views.cse2rem),
        path('cse1rem/', views.cse1rem),
        path('eee4rem/', views.eee4rem),
        path('eee3rem/', views.eee3rem),
        path('eee2rem/', views.eee2rem),
        path('eee1rem/', views.eee1rem),
        path('ece4rem/', views.ece4rem),
        path('ece3rem/', views.ece3rem),
        path('ece2rem/', views.ece2rem),
        path('ece1rem/', views.ece1rem),
        path('it4rem/', views.it4rem),
        path('it3rem/', views.it3rem),
        path('it2rem/', views.it2rem),
        path('it1rem/', views.it1rem),  
        path('csm4rem/', views.csm4rem),
        path('csm3rem/', views.csm3rem),
        path('csm2rem/', views.csm2rem),
        path('csm1rem/', views.csm1rem),  
]